[project]
name = "nlp-basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nltk>=3.9.1",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
[dependency-groups]
dev = [
  "ipykernel>=6.29.5",
  "ipython",
]
